@startuml

class GameConfig {
    -List<Player> blueAgents
    -List<Player> blueSpies
    -List<Player> redAgents
    -List<Player> redSpies
    -int width
    -int height
}
Session --> GameConfig
class Session {
    -ColorTeam redTeam
    -ColorTeam blueTeam
    -Board board
    -List<Clue> clues
    +Game(GameConfig config)
    +getBlueTeam()
    +getRedTeam()
    +setBlueTurn()
    +setRedTurn()
}
ColorTeam --> Session
Clue --> Session
Board --> Session

class Player {
    -String name
    +Player(String name)
}
abstract class Team {
    -Color color
    -List<Player> players
    -Session session
    +Team(Color color, List<Player> players, Session session)
    +getColor()
    +getPlayers()
}
Player --o Team
class AgentTeam extends Team {
    +AgentTeam(List<Player> players, Session session)
    +addClue(Clue newClue)
}
class SpyTeam extends Team {
    +SpyTeam(List<Player> players, Session session)
    +guess(Card card)
}

class ColorTeam {
    -Color color
    -Session session
    -List<Clue> clues
    +ColorTeam(Color color, Session session)
    +getColor()
    +getClues()
    +setSpyTurn()
    +setAgentTurn()
    +endTurn()
    +addClue(Clue clue)
}
SpyTeam --> ColorTeam
AgentTeam --> ColorTeam

class Clue {
    -int word;
    -int count;
}

class Card {
	-String name
	-Color color
	-Boolean revealed
	+Card(String name, Color color)
	+getName()
	+getColor()
	+getRevealed()
	+show()
	+hide()
	+equals(Card card)
}

enum CardState {
    Good,
    Enemy,
    Neutral,
    Forbidden
}
class Board {
	-int width
	-int height
	-Card[][] cards
	+Board(int width, int height, Card[][] cards)
	+getWidth()
	+getHeight()
	+getCard(int x, int y)
    +getState(Card card, Color color)
}
CardState --> Board
Card --o Board

@enduml