@startuml

package codenames.model.game {
    class GameConfig {
        -List<Player> blueAgents
        -List<Player> blueSpies
        -List<Player> redAgents
        -List<Player> redSpies
        -int width
        -int height
    }
    class Session {
        -ColorTeam redTeam
        -ColorTeam blueTeam
        -Board board
        +Session(GameConfig config)
        +getBlueTeam()
        +getRedTeam()
        +setBlueTurn()
        +setRedTurn()
    }
    class Clue {
        -int word;
        -int count;
    }
    class Board {
        -int width
        -int height
        -Card[][] cards
        +Board(int width, int height, Card[][] cards)
        +getWidth()
        +getHeight()
        +getCard(int x, int y)
    }

    codenames.model.game.Session --> codenames.model.game.GameConfig
    codenames.model.colorteam.ColorTeam --> codenames.model.game.Session
    codenames.model.game.Clue --> codenames.model.game.Session
    codenames.model.game.Board --> codenames.model.game.Session
    codenames.model.card.Card --o codenames.model.game.Board
}

package codenames.model.team {
    abstract class Team {
        -List<Player> players
        -Session session
        +Team(CardColor color, List<Player> players, Session session)
        +getColor()
        +getPlayers()
    }
    codenames.model.player.Player --o codenames.model.team.Team
    class AgentTeam extends Team {
        +AgentTeam(List<Player> players, Session session)
        +addClue(Clue newClue)
    }
    class SpyTeam extends codenames.model.team.Team {
        +SpyTeam(List<Player> players, Session session)
        +guess(Card card)
    }
}

package codenames.model.colorteam {
    class ColorTeam {
        -CardColor color
        -Session session
        -List<Clue> clues
        -SpyTeam spyTeam
        -AgentTeam agentTeam
        +ColorTeam(Color color, Session session)
        +getColor()
        +getClues()
        +getSpyTeam()
        +getAgentTeam()
        +setSpyTurn()
        +setAgentTurn()
        +endTurn()
        +addClue(Clue clue)
    }
    SpyTeam --> codenames.model.colorteam.ColorTeam
    AgentTeam --> codenames.model.colorteam.ColorTeam
}

package codenames.model.player {
    class Player {
        -String name
        +Player(String name)
    }
}

package codenames.model.card {
    class Card {
        -String name
        -CardColor color
        -Boolean revealed
        +Card(String name, Color color)
        +getName()
        +getColor()
        +getRevealed()
        +getState(Card card, Color color)
        +show()
        +hide()
        +equals(Card card)
    }
    enum CardColor {
        Blue,
        Red,
        Forbidden,
        Neutral
    }
    enum CardState {
        Good,
        Enemy,
        Neutral,
        Forbidden
    }

    codenames.model.card.CardState --> codenames.model.card.Card
    codenames.model.card.CardColor --> codenames.model.card.Card
}

@enduml